//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.EventGroups = new HashSet<EventGroup>();
        }
    
        public long DeviceID { get; set; }
        public Nullable<System.Guid> RoomID { get; set; }
        public Nullable<System.Guid> EquipmentID { get; set; }
        public string DeviceName { get; set; }
        public string DeviceDescription { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<long> SubSystemID { get; set; }
        public string Software { get; set; }
        public Nullable<int> Lamp1 { get; set; }
        public Nullable<int> Lamp2 { get; set; }
        public Nullable<System.DateTime> HoldMail { get; set; }
        public Nullable<long> Status { get; set; }
    
        public virtual RoomDetail RoomDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventGroup> EventGroups { get; set; }
    }
}
