//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long EventID { get; set; }
        public Nullable<System.Guid> RoomID { get; set; }
        public Nullable<long> DeviceID { get; set; }
        public string EventName { get; set; }
        public string EventType { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string StartID { get; set; }
        public string EndID { get; set; }
        public Nullable<short> minuteson { get; set; }
        public Nullable<long> SourceID { get; set; }
        public string CallID { get; set; }
        public Nullable<short> SourceOn { get; set; }
        public string CallNumber { get; set; }
        public string CallDisconnectReason { get; set; }
        public string CallDisconnectID { get; set; }
        public long EventGroupID { get; set; }
    
        public virtual EventGroup EventGroup { get; set; }
    }
}
