//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cenero_MSCRMEntities2 : DbContext
    {
        public Cenero_MSCRMEntities2()
            : base("name=Cenero_MSCRMEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Incident> Incidents { get; set; }
        public virtual DbSet<New_clientequipmemtipdata> New_clientequipmemtipdata { get; set; }
        public virtual DbSet<New_clientequipment> New_clientequipment { get; set; }
        public virtual DbSet<New_clientroom> New_clientroom { get; set; }
        public virtual DbSet<new_clientrooms_warrantylines> new_clientrooms_warrantylines { get; set; }
        public virtual DbSet<New_Warranty> New_Warranty { get; set; }
        public virtual DbSet<New_WarrantyContract> New_WarrantyContract { get; set; }
    }
}
