//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_WarrantyContract
    {
        public string createdbyyominame { get; set; }
        public string modifiedbyyominame { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public string TransactionCurrencyIdName { get; set; }
        public string New_WarrantyContractContactIdName { get; set; }
        public string CreatedOnBehalfByName { get; set; }
        public string new_SalesRepIdYomiName { get; set; }
        public string CreatedByName { get; set; }
        public string new_CeneroOfficeIdName { get; set; }
        public string New_WarrantyContractOrgIdName { get; set; }
        public string new_CSRIdName { get; set; }
        public string ModifiedByName { get; set; }
        public string new_CSRIdYomiName { get; set; }
        public string new_SalesRepIdName { get; set; }
        public string ModifiedOnBehalfByName { get; set; }
        public System.Guid OwnerId { get; set; }
        public string OwnerIdName { get; set; }
        public string OwnerIdYomiName { get; set; }
        public int OwnerIdDsc { get; set; }
        public Nullable<int> OwnerIdType { get; set; }
        public Nullable<System.Guid> OwningUser { get; set; }
        public Nullable<System.Guid> OwningTeam { get; set; }
        public System.Guid New_WarrantyContractId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public int StateCode { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public byte[] VersionNumber { get; set; }
        public string New_name { get; set; }
        public Nullable<System.Guid> New_WarrantyContractOrgId { get; set; }
        public Nullable<System.Guid> New_WarrantyContractContactId { get; set; }
        public string New_WarrantyContractNumber { get; set; }
        public Nullable<int> New_WarrantyContractType { get; set; }
        public Nullable<System.DateTime> New_ContractStartDate { get; set; }
        public Nullable<System.DateTime> New_ContractEndDate { get; set; }
        public string New_Comments { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<decimal> New_Amount { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> new_amount_Base { get; set; }
        public Nullable<int> New_PerPeriod { get; set; }
        public Nullable<decimal> New_UpfrontAmount { get; set; }
        public Nullable<decimal> new_upfrontamount_Base { get; set; }
        public Nullable<decimal> New_TotalContract { get; set; }
        public Nullable<decimal> new_totalcontract_Base { get; set; }
        public Nullable<decimal> New_Amount2 { get; set; }
        public Nullable<decimal> new_amount2_Base { get; set; }
        public Nullable<int> New_PerPeriod2 { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> new_CSRId { get; set; }
        public Nullable<System.Guid> new_SalesRepId { get; set; }
        public string new_AlertText { get; set; }
        public Nullable<System.DateTime> new_AlertExpiration { get; set; }
        public Nullable<int> new_WarrantyType1 { get; set; }
        public Nullable<int> new_WarrantyType2 { get; set; }
        public Nullable<int> new_ContractLength { get; set; }
        public Nullable<System.Guid> new_CeneroOfficeId { get; set; }
        public Nullable<System.DateTime> new_FiscalYearEnd { get; set; }
        public Nullable<bool> new_Proactive { get; set; }
        public Nullable<bool> new_Reactive { get; set; }
        public Nullable<bool> new_MfgWarranty { get; set; }
        public Nullable<bool> new_Staffing { get; set; }
        public Nullable<int> new_WarrantyType3 { get; set; }
        public Nullable<decimal> new_Amount3 { get; set; }
        public Nullable<decimal> new_amount3_Base { get; set; }
        public Nullable<decimal> new_Amount4 { get; set; }
        public Nullable<decimal> new_amount4_Base { get; set; }
        public Nullable<decimal> new_Total1 { get; set; }
        public Nullable<decimal> new_total1_Base { get; set; }
        public Nullable<decimal> new_Total2 { get; set; }
        public Nullable<decimal> new_total2_Base { get; set; }
        public Nullable<decimal> new_Total3 { get; set; }
        public Nullable<decimal> new_total3_Base { get; set; }
        public Nullable<decimal> new_Total4 { get; set; }
        public Nullable<decimal> new_total4_Base { get; set; }
        public Nullable<int> new_PerPeriod3 { get; set; }
        public Nullable<int> new_PerPeriod4 { get; set; }
        public Nullable<int> new_WarrantyType4 { get; set; }
        public Nullable<bool> new_RoomCheck { get; set; }
        public Nullable<int> new_WarrantyType5 { get; set; }
        public Nullable<decimal> new_Amount5 { get; set; }
        public Nullable<decimal> new_amount5_Base { get; set; }
        public Nullable<decimal> new_Total5 { get; set; }
        public Nullable<decimal> new_total5_Base { get; set; }
        public Nullable<int> new_PerPeriod5 { get; set; }
        public Nullable<System.DateTime> new_PMStartDate { get; set; }
        public Nullable<System.DateTime> new_PMReminderSent { get; set; }
        public Nullable<int> new_PMVisitsperYear { get; set; }
        public Nullable<bool> new_ReactivePlus { get; set; }
    }
}
