//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_Warranty
    {
        public string createdbyyominame { get; set; }
        public string modifiedbyyominame { get; set; }
        public string createdonbehalfbyyominame { get; set; }
        public string modifiedonbehalfbyyominame { get; set; }
        public string new_ServiceRepIdYomiName { get; set; }
        public string new_ServiceRepIdName { get; set; }
        public string New_ProjectIdName { get; set; }
        public string ModifiedByName { get; set; }
        public string New_WarrantyContractToLineIdName { get; set; }
        public string TransactionCurrencyIdName { get; set; }
        public string CreatedOnBehalfByName { get; set; }
        public string ModifiedOnBehalfByName { get; set; }
        public string New_ContactIdName { get; set; }
        public string New_OrganizationIdName { get; set; }
        public string CreatedByName { get; set; }
        public string new_CeneroOfficeIdName { get; set; }
        public System.Guid OwnerId { get; set; }
        public string OwnerIdName { get; set; }
        public string OwnerIdYomiName { get; set; }
        public int OwnerIdDsc { get; set; }
        public Nullable<int> OwnerIdType { get; set; }
        public Nullable<System.Guid> OwningUser { get; set; }
        public Nullable<System.Guid> OwningTeam { get; set; }
        public System.Guid New_WarrantyId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public int StateCode { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public byte[] VersionNumber { get; set; }
        public string New_name { get; set; }
        public Nullable<System.Guid> New_ContactId { get; set; }
        public Nullable<System.Guid> New_OrganizationId { get; set; }
        public Nullable<System.Guid> New_ProjectId { get; set; }
        public string New_SOWNo { get; set; }
        public string New_BoxSaleNo { get; set; }
        public Nullable<System.DateTime> New_StartDate { get; set; }
        public Nullable<System.DateTime> New_EndDate { get; set; }
        public string New_WarrantyNo { get; set; }
        public Nullable<int> New_WarrantyType { get; set; }
        public string New_Comments { get; set; }
        public string New_MfgModel1 { get; set; }
        public string New_MfgModel2 { get; set; }
        public string New_MfgModel3 { get; set; }
        public string New_MfgModel4 { get; set; }
        public string New_MfgModel5 { get; set; }
        public string New_SerialNo1 { get; set; }
        public string New_SerialNo2 { get; set; }
        public string New_SerialNo3 { get; set; }
        public string New_SerialNo4 { get; set; }
        public string New_SerialNo5 { get; set; }
        public string New_ServiceContactPhone { get; set; }
        public string New_Notes { get; set; }
        public string New_Roomname { get; set; }
        public string New_RoomNumber { get; set; }
        public Nullable<System.Guid> New_WarrantyContractToLineId { get; set; }
        public string New_Building { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public string New_Key1 { get; set; }
        public string New_Key2 { get; set; }
        public string New_Key3 { get; set; }
        public string New_Key4 { get; set; }
        public string New_Key5 { get; set; }
        public string New_OldWarrantyType { get; set; }
        public string New_ManufacturerContractNumber { get; set; }
        public string New_PONumber { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> new_ServiceRepId { get; set; }
        public Nullable<System.Guid> new_CeneroOfficeId { get; set; }
        public Nullable<bool> new_Proactive { get; set; }
        public Nullable<bool> new_Reactive { get; set; }
        public Nullable<bool> new_Mfg { get; set; }
        public Nullable<bool> new_Staffing { get; set; }
        public Nullable<bool> new_RoomCheck { get; set; }
        public Nullable<int> new_WarrantyType1 { get; set; }
        public Nullable<decimal> new_Total1 { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> new_total1_Base { get; set; }
        public Nullable<decimal> new_Amount1 { get; set; }
        public Nullable<decimal> new_amount1_Base { get; set; }
        public Nullable<int> new_PerPeriod1 { get; set; }
        public Nullable<bool> new_TimeandMaterials { get; set; }
        public Nullable<bool> new_Custom { get; set; }
        public Nullable<int> new_WarrantyType2 { get; set; }
        public Nullable<decimal> new_Total2 { get; set; }
        public Nullable<decimal> new_total2_Base { get; set; }
        public Nullable<decimal> new_Amount2 { get; set; }
        public Nullable<decimal> new_amount2_Base { get; set; }
        public Nullable<int> new_PerPeriod2 { get; set; }
        public Nullable<int> new_PMVisitsperYear { get; set; }
        public Nullable<System.DateTime> new_PMStartDate { get; set; }
        public Nullable<System.DateTime> new_PMReminderSent { get; set; }
        public Nullable<System.DateTime> new_NextPMDate { get; set; }
        public Nullable<bool> new_ReactivePlus { get; set; }
    }
}
