//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_clientroom_projectfile
    {
        public System.Guid new_clientroom_projectfileId { get; set; }
        public byte[] VersionNumber { get; set; }
        public System.Guid new_clientroomid { get; set; }
        public System.Guid new_projectfileid { get; set; }
    }
}
