//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomDetail()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public System.Guid CRMRoomID { get; set; }
        public string RoomName { get; set; }
        public string RoomDescription { get; set; }
        public Nullable<System.Guid> CRMOwnerID { get; set; }
        public Nullable<bool> RoomCheckReady { get; set; }
        public Nullable<bool> Dashboard_2 { get; set; }
        public Nullable<bool> Dashboard_3 { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<short> UTCOffset { get; set; }
        public Nullable<short> TestOffset { get; set; }
        public int Status { get; set; }
        public int ServicePlan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
        public virtual RoomSummary RoomSummary { get; set; }
    }
}
