//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomSummary
    {
        public long LineID { get; set; }
        public System.Guid RoomID { get; set; }
        public string RoomName { get; set; }
        public Nullable<short> VTCStatus { get; set; }
        public Nullable<short> ATCStatus { get; set; }
        public Nullable<short> ControlStatus { get; set; }
        public Nullable<short> PresentationStatus { get; set; }
        public Nullable<short> OnlineStatus { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<System.Guid> CRM_ProjectRoomID { get; set; }
        public Nullable<System.Guid> RoomView_RoomID { get; set; }
    
        public virtual RoomDetail RoomDetail { get; set; }
    }
}
